[package]
name = "manta-backend-dispatcher"
version = "0.1.66"
edition = "2021"
license-file = "LICENSE"
description = "Traits to be developed by Mesa backends"
documentation = "https://github.com/eth-cscs/manta-backend-dispatcher/blob/main/README.md"
homepage = "https://github.com/eth-cscs/manta-backend-dispatcher/blob/main/README.md"
repository = "https://github.com/eth-cscs/manta-backend-dispatcher"

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls", "socks"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.56"
log = "0.4.17"
uuid = "1.6.1"
strum = { version = "0.25.0", default-features = false }
strum_macros = "0.25"
# kube = { version = "0.87.2", features = ["ws"] }
# k8s-openapi = { version = "0.20.0", features = ["v1_26"] }
# futures = { version = "0.3.28", default-features = false }
futures-io = "0.3.31"
# futures-util = "0.3.28"
tokio = { version = "1.14", features = ["full"] }
serde_yaml = "0.9.17"
rdkafka = { version = "0.37", features = ["cmake-build"] }
chrono = { version = "0.4.31", default-features = false }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
