[package]
name = "backend-dispatcher"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "Traits to be developed by Mesa backends"

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.56"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls", "socks"] }
